In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
data = np.random.randn(4,3)

In [6]:
data

array([[ 0.86704347,  1.66325465,  0.27480306],
       [-1.55177354, -0.35524978, -1.01496957],
       [-0.44018881, -0.55579829, -1.48619906],
       [-0.78967531, -1.62162344,  0.89620499]])

In [7]:
# pd.Series(data) # does not work because Series works for 1 dimensional ( 1 row )

In [8]:
data_frame = pd.DataFrame(data)

In [9]:
data_frame

          0         1         2
0  0.867043  1.663255  0.274803
1 -1.551774 -0.355250 -1.014970
2 -0.440189 -0.555798 -1.486199
3 -0.789675 -1.621623  0.896205

In [10]:
type(data_frame)

pandas.core.frame.DataFrame

In [11]:
type(data_frame[0])

pandas.core.series.Series

In [12]:
new_df = pd.DataFrame(data, index = ["Eylul","Ali","Jane","Hannah"], columns = ["Salary","Age","Seniorty"])
# data is the data variable we created earlier

In [13]:
new_df

          Salary       Age  Seniorty
Eylul   0.867043  1.663255  0.274803
Ali    -1.551774 -0.355250 -1.014970
Jane   -0.440189 -0.555798 -1.486199
Hannah -0.789675 -1.621623  0.896205

In [21]:
new_df["Salary"]

Eylul     0.867043
Ali      -1.551774
Jane     -0.440189
Hannah   -0.789675
Name: Salary, dtype: float64

In [35]:
new_df.loc["Eylul"] # with []

Salary      0.867043
Age         1.663255
Seniorty    0.274803
Name: Eylul, dtype: float64

In [36]:
data_frame.iloc[0] # if there is integer indexes

0    0.867043
1    1.663255
2    0.274803
Name: 0, dtype: float64

In [37]:
# it also uses in other indexes

new_df.iloc[2]

Salary     -0.440189
Age        -0.555798
Seniorty   -1.486199
Name: Jane, dtype: float64

In [38]:
new_df.iloc[:,0] # returns every rows and first columns

Eylul     0.867043
Ali      -1.551774
Jane     -0.440189
Hannah   -0.789675
Name: Salary, dtype: float64

In [58]:
new_df["Extra"] = 10
new_df

          Salary       Age  Seniorty  Extra
Eylul   0.867043  1.663255  0.274803     10
Ali    -1.551774 -0.355250 -1.014970     10
Jane   -0.440189 -0.555798 -1.486199     10
Hannah -0.789675 -1.621623  0.896205     10

In [59]:
new_df = new_df.drop("Extra", axis = 1)
# axis = 0 means Rows
# axis = 1 means Columns

# default value = 0

In [60]:
new_df

          Salary       Age  Seniorty
Eylul   0.867043  1.663255  0.274803
Ali    -1.551774 -0.355250 -1.014970
Jane   -0.440189 -0.555798 -1.486199
Hannah -0.789675 -1.621623  0.896205

In [61]:
new_df["City"] = "New York"
new_df

          Salary       Age  Seniorty      City
Eylul   0.867043  1.663255  0.274803  New York
Ali    -1.551774 -0.355250 -1.014970  New York
Jane   -0.440189 -0.555798 -1.486199  New York
Hannah -0.789675 -1.621623  0.896205  New York

In [62]:
# do this instead

new_df.drop("City", axis = 1, inplace = True)

In [63]:
new_df

          Salary       Age  Seniorty
Eylul   0.867043  1.663255  0.274803
Ali    -1.551774 -0.355250 -1.014970
Jane   -0.440189 -0.555798 -1.486199
Hannah -0.789675 -1.621623  0.896205

In [65]:
# default axis value is 0
# default inplace value is False

new_df.drop("Hannah", axis = 0, inplace = True)

In [66]:
new_df

         Salary       Age  Seniorty
Eylul  0.867043  1.663255  0.274803
Ali   -1.551774 -0.355250 -1.014970
Jane  -0.440189 -0.555798 -1.486199

In [68]:
print(new_df.iloc[1]["Age"])

-0.35524978219012443

In [69]:
# or
print(new_df.loc["Ali","Age"])

-0.35524978219012443

In [70]:
new_df.loc["Ali","Age"] = 21

In [71]:
new_df

         Salary        Age  Seniorty
Eylul  0.867043   1.663255  0.274803
Ali   -1.551774  21.000000 -1.014970
Jane  -0.440189  -0.555798 -1.486199

In [72]:
new_df[new_df > 0]

         Salary        Age  Seniorty
Eylul  0.867043   1.663255  0.274803
Ali         NaN  21.000000       NaN
Jane        NaN        NaN       NaN

In [75]:
new_df[new_df["Salary"] > 0]

         Salary       Age  Seniorty
Eylul  0.867043  1.663255  0.274803

In [79]:
reset_frame = new_df.reset_index()
reset_frame

   index    Salary        Age  Seniorty
0  Eylul  0.867043   1.663255  0.274803
1    Ali -1.551774  21.000000 -1.014970
2   Jane -0.440189  -0.555798 -1.486199

In [80]:
reset_frame.loc[0]

index          Eylul
Salary      0.867043
Age         1.663255
Seniorty    0.274803
Name: 0, dtype: object

In [85]:
new_df.loc["Hannah"] = [40000,20,"Dr."]
new_df

              Salary        Age  Seniorty
Eylul       0.867043   1.663255  0.274803
Ali        -1.551774  21.000000  -1.01497
Jane       -0.440189  -0.555798 -1.486199
Hannah  40000.000000  20.000000       Dr.

In [87]:
new_indices = ["eyl","al","ja","han"]

In [95]:
new_df["New Index"] = new_indices

In [99]:
new_df

              Salary        Age  Seniorty New Index
Eylul       0.867043   1.663255  0.274803       eyl
Ali        -1.551774  21.000000  -1.01497        al
Jane       -0.440189  -0.555798 -1.486199        ja
Hannah  40000.000000  20.000000       Dr.       han

In [100]:
new_df.set_index("New Index", inplace=True)

In [101]:
new_df

                 Salary        Age  Seniorty
New Index
eyl            0.867043   1.663255  0.274803
al            -1.551774  21.000000  -1.01497
ja            -0.440189  -0.555798 -1.486199
han        40000.000000  20.000000       Dr.

In [102]:
new_df.index

Index(['eyl', 'al', 'ja', 'han'], dtype='object', name='New Index')

In [103]:
new_df.loc["al"]

Salary     -1.551774
Age             21.0
Seniorty    -1.01497
Name: al, dtype: object

In [107]:
# multi index

In [108]:
first_index = ["bencik","bencik","bencik","atici","atici","atici"]

In [112]:
second_index = ["ela","eylul","umit","yagiz","yusuf","nilufer"]

In [113]:
zipped_index = list(zip(first_index,second_index))
zipped_index

[('bencik', 'ela'),
 ('bencik', 'eylul'),
 ('bencik', 'umit'),
 ('atici', 'yagiz'),
 ('atici', 'yusuf'),
 ('atici', 'nilufer')]

In [114]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [115]:
zipped_index

MultiIndex([('bencik',     'ela'),
            ('bencik',   'eylul'),
            ('bencik',    'umit'),
            ( 'atici',   'yagiz'),
            ( 'atici',   'yusuf'),
            ( 'atici', 'nilufer')],
           )

In [125]:
sample_values = np.ones((6,3))

In [126]:
big_df = pd.DataFrame(sample_values, index = zipped_index, columns = ["age","gender","birth year"])

In [127]:
big_df

                age  gender  birth year
bencik ela      1.0     1.0         1.0
       eylul    1.0     1.0         1.0
       umit     1.0     1.0         1.0
atici  yagiz    1.0     1.0         1.0
       yusuf    1.0     1.0         1.0
       nilufer  1.0     1.0         1.0

In [128]:
big_df.loc["bencik"].loc["ela"]

age           1.0
gender        1.0
birth year    1.0
Name: ela, dtype: float64

In [132]:
# for changing values

# Just updates "bencik" -> "ela" 
big_df.loc[("bencik", "ela"), :] = [24, "female", "2002"]

In [133]:
big_df

                 age  gender birth year
bencik ela      24.0  female       2002
       eylul     1.0     1.0        1.0
       umit      1.0     1.0        1.0
atici  yagiz     1.0     1.0        1.0
       yusuf     1.0     1.0        1.0
       nilufer   1.0     1.0        1.0